### ISSUE TITLE
Help file examples not running

### ISSUE THREAD

**Issue by svanomm** [JanDitzen/xtbreak#16]
Hello, I have installed the latest version of the package with "net install xtbreak, from(https://janditzen.github.io/xtbreak/)". However, many of the examples in the help file do not run for me and return error messages. In the first example, after running "xtbreak deaths L1.cases", I get the error message "Number of covariates (2) too small relative to minimal segment length with trimming of .15 to estimate model." I was not able to specify a value of trimming() that fixed the command.

Edit: I am using Stata version 18 with the latest update (04apr2024).

**Comment by JanDitzen** [comment]
Dear Steven,
thank you very much for your interest in xtbreak. There was a bug in a check which is solved with version 1.5. Can you please update xtbreak and let me know if it works now.
Best,
Jan

**Comment by svanomm** [comment]
Hi Jan, I had to uninstall multiple versions of xtbreak saved to my machine using "ado update" and "ado uninstall" (note that Stata reports "cannot tell because distribution dates not provided by source" for the package). Now the package appears to be working! Thanks so much for your quick response.
