### ISSUE TITLE
Professor

### ISSUE THREAD

**Issue by BernardFingleton** [JanDitzen/xtbreak#17]
Dear JanDitzen
what I am getting in stata is

. use https://github.com/JanDitzen/xtbreak/blob/main/data/US.dta
file https://github.com/JanDitzen/xtbreak/blob/main/data/US.dta not Stata format

Is it a problem that you can fix?
Sincerely
Bernard Fingleton

**Comment by JanDitzen** [comment]
Dear Professor Fingleton,
can you please try 

```use  https://github.com/JanDitzen/xtbreak/raw/main/data/US.dta``

Best,

Jan Ditzen
