### ISSUE TITLE
Professor

### ISSUE THREAD

**Issue by BernardFingleton** [JanDitzen/xtbreak#18]
Thanks for your previous quick reply, but now I'm getting

. xtbreak deaths L.cases, vce(hac) csa(L.cases) trimming(0.1)
        xtbreak_solver():  3301  subscript invalid
  xtbreak_m_partialout():     -  function returned error
xtbreak_mult_partialout():     -  function returned error
xtbreak_GetBreakPoints():     -  function returned error
xtbreak_Test_Hiii_unknown():     -  function returned error
                 <istmt>:     -  function returned error
Sincerely
Bernard Fingleton

**Comment by JanDitzen** [comment]
Dear Professor Fingleton,

the file "US.dta" is a time series dataset. The option csa() (and csd and csanobreaks()) can only be used on panel datasets.  Please remove the option. Alternatively you can use the dataset "US_panel.dta" if you are interested int he examples for a panel dataset.

The next version of xtbreak will automatically ignore those options and not crash. 

Thank you very much for raising the error.

Best,

Jan Ditzen
